settings:
  REWARD: 50
msg:
  NO_PERM: '&2Puzzles &8» &fYou dont have permissions'
  CONFIG_RELOADED: '&2Puzzles &8» &fConfig reloaded!'
  GUESS_TEXT: '&2Puzzles &8» &fGuess this puzzle: &6%puzzle%'
  GUESS_MATH: '&2Puzzles &8» &fGuess this math: &6%first% &f+ &6%second%'
  NO_PUZZLE: '&2Puzzles &8» &fThere is no puzzle or math given!'
  REPEAT: '&2Puzzles &8» &fRepeating question:'
  CORRECT_BROADCAST: '&2Puzzles &8» &a✓ &6%player% &fanswered correctly!'
  CORRECT: '&2Puzzles &8» &a✓ &fYou gave correct answer!'
questions:
  #  - Answer/Question
  # Answer, that player need to guess/Question, that displayed in the chat
  # This is russian simples:
  - Cамовар/У какого молодца вечно капает с конца?
  - Антенна/Стою на крыше, всех труб выше.
  - Балалайка/В лесу тяп-тяп, дома ляп-ляп, на колени возьмешь - заплачет.
  - Вдова/Только она всегда точно знает, где её муж. Кто она?
  - Вдох/Я легкий как перышко, но долго меня не удержишь.
  - Веки/Волос на волос, тело на тело и начинается темное дело.
  - Весы/Что за судья без языка?
  - Время/Вчера было, сегодня есть и завтра будет.
  - Время/Что возвратить нельзя?
  - Гнездо/Без рук, без топоренка, построена избенка.
  - Гром/Конь бежит, Земля дрожит.
  - Гусь/В воде купался, сух остался.
  - Да нет наверное/Как «Да» произнести как «Нет»?
  - День/К вечеру умирает, по утру оживает.
  - Долги/Сами не горят, а их гасить все равно приходится.
  - Запасное/Какое колесо не крутится при правом развороте?
  - Зарплата/Не лёд, а тает, не лодка, а уплывает.
  - Зима/Она покрыта белой бумагой и листьев нет на деревьях что же это за мадам?
  - Зубы и язык/У тридцати двух воинов один командир.
  - Из пустой/Из какой посуды нельзя ничего поесть?
  - Кастрюля/Возле тела уши, а головы нет.
  - Клубок/С хвостом, а за хвост не поднимешь.
  - Ковш/Утка в море, хвост на заборе.
  - Кочерга/Железная нога – это...
  - Курица/Сидит птах на белых горах, дожидается из мертвого живого.
  - Лестница/Лежит на спине - никому не нужна. Прислони к стене - пригодится она.
  - Ложка/Каким инструментом можно щи хлебать?
  - Месяц/Рогатый, а не бодается.
  - Ми-ля-ми/Какими нотами можно измерить расстояние?
  - Молния/Раскаленная стрела дуб свалила у села.
  - Молоток/Сам худ, а голова с пуд.
  - Море/Кругом вода, а с питьем беда.
  - Морской/Какой болезнью никто не болеет на суше?
  - Мост/Я над речкой лежу, оба берега держу.
  - Мяч/Очень любят молодца, а бьют, колотят без конца.
  - Наушники/На ушах висят, а не сережки.
  - Ноги/Куда ни пойдешь - все на них взглянешь.
  - Нос/Между двух светил сижу я один.
  - Обед и ужин/Что нельзя съесть на завтрак?
  - Пальцы/Пять братьев - годами равные, ростом разные.
  - Петух/Два раза родился, ни разу не крестилка, всем людям пророк.
  - Петух/Из белого камня родится, весь свет будит.
  - Петух/Какая птица яиц не несет, но сама с них вылупливается?
  - Петух/Кто больше всех кричит, а меньше всех делает.
  - Петух/Не ездок, а со шпорами, не сторож, а всех будит.
  - Петух/Сидел на заборе, пел да кричал, а как все собрались, взял да замолчал.
  - Петушиным/Каким гребешком никто не причесывается?
  - Подушка/Два брюшка, четыре ушка.
  - Почтовый ящик/Дом из жести, а жильцы в нем - вести.
  - Пылесос/Пыль увижу - заворчу, заверчу и проглочу.
  - Работа/Что человек делать не хочет, но также не хочет это терять?
  - Радио/Без языка живет, не ест и не пьет, а говорит и поет.
  - Радио/В Москве говорят, а у нас слышно.
  - Расческа/Зубов много, а ничего не ест.
  - Расческа/Что достанет зубами затылок?
  - Река/В нее льется, из нее льется, сама по земле плетется.
  - Река/Течет-течет - не вытечет; бежит-бежит - не выбежит.
  - И/Что находится между горой и долиной?
  - Решето/Новая посудина, а вся в дырах.
  - Рот/Что за обедом всего нужнее?
  - Санки/Под гору - коняшка, в гору - деревяшка.
  - Свеча/Стоит столбом, горит огнем, ни жару, ни пару, ни угольев.
  - Седло/На чужой спине едет, а на своей груз везет.
  - Синичка/Синяя косынка, темненькая спинка. Маленькая птичка, звать её...
  - Скворец/На шесте - дворец, во дворце - певец.
  - Снежок/Ты помни его немножко, станет твердым как картошка.
  - Сова/Днем спит, ночью летает.
  - Сон/И рать, и воеводу - всех повалил.
  - Сон/Что слаще всего на свете?
  - Столб/Стоп-бревно в случае экстренного торможения.
  - Троллейбус/Что это такое - синий, большой, с усами и полностью набит зайцами?
  - Тропинка/Все меня топчут, а я все лучше.
  - Фамилия/У Шварценеггера это длинное, у Джеки Чана короткое, у Мадонны вообще нет, а Папа Римский давно этим не пользуется.
  - Фрегат/Какая птица носит название корабля?
  - Цепь/Не лает, не кусает, а к будке привязана.
  - Цепь/Узловат Кузьма, развязать нельзя.
  - Чайник/В брюхе – баня, в носу – решето, на голове – пуп. Рука одна, да и та на спине. Что это?
  - Шахматный/Какой конь не ест овса?
  - Ядро/Что находится в центре Земли?
  - Язык/Золотое решето, черных домиков полно
  - Якорь/Когда он нужен, его выбрасывают. Когда не нужен – поднимают.
  - Ямайка/Остров, выдающий себя за одежду.